mymessanger/mymessanger/apps/mesdb/urls.py
from django.urls import path, re_path

from . import views

app_name = "mesdb"

urlpatterns = [
	path('index/message/<int:chats_id>/', views.chats, name = 'index-chat'),
	path('index/new_chat/<int:chat_id>/', views.findedchat, name = 'findedchat'),
	path('index/<str:searching>/', views.get_chats, name = 'perestax'),
	path('login/', views.LoginFormView.as_view(), name = 'login'),
	path('logout/', views.user_logout, name = 'logout'),
	path('regestration/', views.RegisterFormView.as_view(), name = 'reg'),
	path('index/', views.main, name = 'index'),
	path('sendmessage/', views.send_message, name = 'sendmessage'),
	path('main/', views.main, name = 'main'),
	path('index/change_day/<int:day_number>/', views.change_day, name = 'change_day' ),
	path('edit_hw/', views.edit_hw, name = 'edit_hw'),
	re_path(r'^getmessage/', views.get_message, name = 'getmessage'),
]

mymessanger/mymessanger/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('messanger/', include('mesdb.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mymessanger/mymessanger/apps/mesdb/models.py
from django.db import models
from time import time


class User(models.Model):
    user_login = models.CharField('Логин пользователя', max_length=30)
    grade = models.IntegerField("Параллель", default=-1)
    class_letter = models.CharField("Буква класса", max_length=1, default="G")
    user_avatar = models.ImageField(default='../../static/img/def.jpg', upload_to='avatars/')
    is_it_bot = models.BooleanField("Это BOT?", default=False)

    def __str__(self):
        return self.user_login

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class Chat(models.Model):
    chat_users = models.ManyToManyField(User)
    chat_title = models.CharField('Название чата', max_length=30)
    chat_class = models.BooleanField("Это класс?", default=False)

    def __str__(self):
        return self.chat_title

    class Meta:
        verbose_name = 'Чат'
        verbose_name_plural = 'Чаты'


class Message(models.Model):
    unread = models.ManyToManyField(User)
    message_chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    message_author_id = models.IntegerField('id')
    message_text = models.TextField('Текст сообщения')
    message_time = models.IntegerField(default=time())

    def __str__(self):
        return self.message_text

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Homework(models.Model):
    day_number = models.IntegerField('Номер дня в учебном году')

    class_1 = models.CharField('1 урок', max_length=20, default="Физика")
    class_2 = models.CharField('2 урок', max_length=20, default="Физика")
    class_3 = models.CharField('3 урок', max_length=20, default="Физика")
    class_4 = models.CharField('4 урок', max_length=20, default="Физика")
    class_5 = models.CharField('5 урок', max_length=20, default="Физика")
    class_6 = models.CharField('6 урок', max_length=20, default="Физика")
    class_7 = models.CharField('7 урок', max_length=20, default="Физика")
    class_8 = models.CharField('8 урок', max_length=20, default="Физика")

    task_1 = models.TextField('задание на 1 урок', default="Физика")
    task_2 = models.TextField('задание на 1 урок', default="Физика")
    task_3 = models.TextField('задание на 1 урок', default="Физика")
    task_4 = models.TextField('задание на 1 урок', default="Физика")
    task_5 = models.TextField('задание на 1 урок', default="Физика")
    task_6 = models.TextField('задание на 1 урок', default="Физика")
    task_7 = models.TextField('задание на 1 урок', default="Физика")
    task_8 = models.TextField('задание на 1 урок', default="Физика")

    description_1 = models.TextField('Пояснение к уроку 1', default="Физика")
    description_2 = models.TextField('Пояснение к уроку 2', default="Физика")
    description_3 = models.TextField('Пояснение к уроку 3', default="Физика")
    description_4 = models.TextField('Пояснение к уроку 4', default="Физика")
    description_5 = models.TextField('Пояснение к уроку 5', default="Физика")
    description_6 = models.TextField('Пояснение к уроку 6', default="Физика")
    description_7 = models.TextField('Пояснение к уроку 7', default="Физика")
    description_8 = models.TextField('Пояснение к уроку 8', default="Физика")

    homework_chat = models.ForeignKey(Chat, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.homework_chat) + " " +str(self.day_number)

    class Meta:
        verbose_name = 'Домашнее задание'
        verbose_name_plural = 'Домашние задания'

mymessanger/mymessanger/apps/mesdb/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
import time
import requests
from .models import Message, User, Chat


def count_day_number():
    year = int(time.strftime("%Y", time.gmtime(time.time())))
    month = int(time.strftime("%m", time.gmtime(time.time())))
    day = int(time.strftime("%d", time.gmtime(time.time())))
    if year % 4 == 0 and year % 100 != 0 or year % 400 == 0:
        flag = 1
    else:
        flag = 0
    d = [30, 31, 30, 31, 31, 28 + flag, 31, 30, 31]  # колво дней в месяцах с сентября по май
    if month == 9:
        day_number = day
    elif month > 9:
        day_number = sum(d[:month - 9]) + day
    else:
        day_number = sum(d[:12 - (8 - month)])

    return day_number


def found_data(the_user):
    the_user_chats = the_user.chat_set.all()
    data = []

    for i in range(len(the_user_chats)):

        TCU = the_user_chats[i].chat_users.all()
        if len(TCU) == 2:
            if TCU[0].user_login == the_user.user_login:
                data_name = TCU[1].user_login
                data_avatar = TCU[1].user_avatar
            else:
                data_name = TCU[0].user_login
                data_avatar = TCU[0].user_avatar
        else:
            data_name = the_user_chats[i].chat_title
            data_avatar = the_user.user_avatar
        the_user_chats_messages = the_user_chats[i].message_set.all()
        last_message_text = ""
        last_message_unread = 0
        last_message_time_timestamp = time.time()
        if len(the_user_chats_messages) - 1 > 0:
            last_message_text = the_user_chats_messages[len(the_user_chats_messages) - 1].message_text
            last_message_unread = len(the_user_chats_messages[len(the_user_chats_messages) - 1].unread.all())
            last_message_time_timestamp = int(the_user_chats_messages[len(the_user_chats_messages) - 1].message_time)
        last_message_time_struct_time = time.localtime(last_message_time_timestamp)
        if time.strftime("%Y", last_message_time_struct_time) == time.strftime("%Y", time.localtime(time.time())):
            if time.strftime("%b", last_message_time_struct_time) == time.strftime("%b", time.localtime(time.time())):
                if time.strftime("%d", last_message_time_struct_time) == time.strftime("%d",
                                                                                       time.localtime(time.time())):
                    last_message_time = time.strftime("%H:%M", last_message_time_struct_time)
                else:
                    last_message_time = time.strftime("%a, %d", last_message_time_struct_time)
            else:
                last_message_time = time.strftime("%b, %d", last_message_time_struct_time)
        else:
            last_message_time = time.strftime("%Y, %b", last_message_time_struct_time)

        table_chat = the_user.chat_set.get(chat_class=True)

        data.append({
            'name': data_name,
            'avatar': data_avatar,
            'id': the_user_chats[i].id,
            'last_message': last_message_text,
            'last_message_time': last_message_time,
            'last_message_unread': last_message_unread,
        })

    return data, table_chat


def main(request):
    if not request.user.is_authenticated:
        return render(request, 'mesdb/login.html')
    the_user_id = request.user.id
    the_user = User.objects.get(id=the_user_id)

    day_number = count_day_number()  # вычисление даты таблицы
    data, table_chat = found_data(the_user)
    hw_table = {
        "table_chat": table_chat.homework_set.get(day_number=day_number),
        "day_number": day_number
    }

    return render(request, 'mesdb/index.html', {'data': data, 'me': the_user, 'hw_table': hw_table, })


def get_chats(request, searching):
    the_user_id = request.user.id
    the_user = User.objects.get(id=the_user_id)
    the_user_chats = the_user.chat_set.all()
    result_users = User.objects.filter(user_login__contains=searching)
    x = 0
    json = {}
    old = False
    for i in result_users:
        if i == the_user:
            continue
        for j in the_user_chats:
            if len(j.chat_users.all()) == 2:
                if i in j.chat_users.all():
                    old = True
                    break
        if not old:
            json[str(x)] = [i.user_login, i.id]
            x += 1
            old = False
    return JsonResponse(json, safe=False)


def findedchat(request, chat_id):
    the_user_id = request.user.id
    the_user = User.objects.get(id=the_user_id)
    opponent = User.objects.get(id=chat_id)
    new_chat = Chat(
        chat_title=the_user.user_login + '*' + opponent.user_login
    )
    new_chat.save()
    new_chat.chat_users.add(the_user)
    new_chat.chat_users.add(opponent)
    a = Chat.objects.get(id=new_chat.id)
    b = a.message_set.all()
    c = a.chat_users.all()
    op = a.chat_title
    if len(c) == 2:
        op = (c[1] if c[0].user_login == the_user.user_login else c[0])
    json = {}
    json["chat"] = [a.id, a.chat_title]
    json["messages"] = []
    for i in b:
        json["messages"].append([i.message_author_id, i.message_text])
    json["me"] = int(the_user_id)
    json["opname"] = str(op)

    return JsonResponse(json, safe=False)


def chats(request, chats_id):
    if not request.user.is_authenticated:
        return render(request, 'mesdb/login.html')
    the_user_id = request.user.id
    the_user = User.objects.get(id=the_user_id)
    the_user_chat = the_user.chat_set.get(id=chats_id)
    a = the_user_chat
    b = a.message_set.all()
    c = a.chat_users.all()
    op = a.chat_title
    if len(c) == 2:
        op = (c[1] if c[0].user_login == the_user.user_login else c[0])
    json = {}
    json["chat"] = [a.id, a.chat_title]
    json["messages"] = []
    for i in b:
        json["messages"].append(
            [i.message_author_id, i.message_text, i.message_time])
    json["me"] = int(the_user_id)
    json["opname"] = str(op)

    return JsonResponse(json, safe=False)


def index(request):
    if not request.user.is_authenticated:
        return redirect('login/')
    else:
        return redirect('chats/')


class RegisterFormView(FormView):
    form_class = UserCreationForm

    success_url = "/messanger/index"

    template_name = "mesdb/register.html"

    def form_valid(self, form):
        form.save()
        username = self.request.POST['username']
        password = self.request.POST['password1']
        # authenticate user then login
        us = authenticate(username=username, password=password)
        login(self.request, us)
        new_user = User(user_login=username)
        new_user.save()
        return super(RegisterFormView, self).form_valid(form)


class LoginFormView(FormView):
    form_class = AuthenticationForm

    template_name = "mesdb/login.html"

    success_url = "/messanger/index"

    def form_valid(self, form):
        self.user = form.get_user()
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)


def user_logout(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect('login/')


def send_message(request):
    to_chat_id = request.POST.get('to_user', None)
    to_chat = Chat.objects.get(id=to_chat_id)
    new_message = request.POST.get('message', None)
    the_user_id = request.user.id
    add_new_message = Message(
        message_chat=to_chat,
        message_author_id=the_user_id,
        message_text=new_message,
        message_time=time.time()
    )
    add_new_message.save()
    notify_users = to_chat.chat_users.exclude(id=the_user_id)
    add_new_message.unread.set(notify_users)

    for i in to_chat.chat_users.all():
        if i.is_it_bot:
            response = requests.post('https://cubebattle.ru/supermess.php', data={
                'text': new_message,
                'author_id': the_user_id,
                'chat_id': to_chat_id,
                'amount_chat_members': len(to_chat.chat_users.all()),
            })
            print(response)

    return JsonResponse({})


def get_message(request):
    the_user_id = request.user.id
    the_user = User.objects.get(id=the_user_id)
    list_messages = the_user.message_set.all()
    list_json = {}
    if not list_messages:
        return JsonResponse(list_json)
    for i in range(len(list_messages)):
        list_json[str(i)] = {
            'message_chat_id': list_messages[i].message_chat.id,
            'author_id': list_messages[i].message_author_id,
            'message_text': list_messages[i].message_text,
            'message_time': time.strftime("%H:%M", time.localtime(list_messages[i].message_time))
        }
    for i in range(len(list_messages)):
        list_messages[i].unread.clear()
    return JsonResponse(list_json)


def change_day(request, day_number):
    the_user_id = request.user.id
    the_user = User.objects.get(id=the_user_id)
    the_user_chat_class = the_user.chat_set.get(chat_class=True)
    last_hw_table = the_user_chat_class.homework_set.get(day_number=day_number)

    json = {"lessons": [last_hw_table.class_1, last_hw_table.class_2, last_hw_table.class_3, last_hw_table.class_4,
                        last_hw_table.class_5, last_hw_table.class_6, last_hw_table.class_7, last_hw_table.class_8],

            "tasks": [last_hw_table.task_1, last_hw_table.task_2, last_hw_table.task_3, last_hw_table.task_4,
                      last_hw_table.task_5, last_hw_table.task_6, last_hw_table.task_7, last_hw_table.task_8],

            "descriptions": [last_hw_table.description_1, last_hw_table.description_2, last_hw_table.description_3,
                             last_hw_table.description_4, last_hw_table.description_5, last_hw_table.description_6,

mymessanger/mymessanger/templates/mesdb/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Главная Kaniti{% endblock %}

{% block stylesheets%} 
	<link rel="stylesheet" href="{% static 'css/index.css' %}">
	<link rel="stylesheet" href="{% static 'css/adaptive.css' %}">
{% endblock %}

{% block content %}

	<div class="sidebar">

	</div>
	<div class="main">
		
		<div class="header">
			<h1 class="time">17:00</h1>
			
			<div class="profile">
				<div class="homework" day-Link="{% url 'mesdb:change_day' hw_table.day_number %}" day-number="{{hw_table.day_number}}">
					табличка

					<div id="HW-Modal">
						<p class="model-title">Домашнее задание / расписание</p>
						<button class="edit-hw__button" active="false">
							<img src="{% static 'img/edit.png' %}" class="edit-hw__img">
						</button>
						<a href="#" class="last-day">←</a>
						<table class="homework-table">
							<tr>
								<td class="class c-title">Предмет</td>
								<td class="task t-title">Задание</td>
								<td class="description d-title">Описание урока</td>
							</tr>
							<tr>
								<td class="class c1">{{hw_table.table_chat.class_1 }}</td>
								<td class="task t1">{{hw_table.table_chat.task_1}}</td>
								<td class="description d1">{{hw_table.table_chat.description_1}}</td>
							</tr>
							<tr>
								<td class="class c2">{{hw_table.table_chat.class_2 }}</td>
								<td class="task t2">{{hw_table.table_chat.task_2}}</td>
								<td class="description d2">{{hw_table.table_chat.description_2}}</td>
							</tr>
							<tr>
								<td class="class c3">{{hw_table.table_chat.class_3 }}</td>
								<td class="task t3">{{hw_table.table_chat.task_3}}</td>
								<td class="description d3">{{hw_table.table_chat.description_3}}</td>
							</tr>
							<tr>
								<td class="class c4">{{hw_table.table_chat.class_4 }}</td>
								<td class="task t4">{{hw_table.table_chat.task_4}}</td>
								<td class="description d4">{{hw_table.table_chat.description_4}}</td>
							</tr>
							<tr>
								<td class="class c5">{{hw_table.table_chat.class_5 }}</td>
								<td class="task t5">{{hw_table.table_chat.task_5}}</td>
								<td class="description d5">{{hw_table.table_chat.description_5}}</td>
							</tr>
							<tr>
								<td class="class c6">{{hw_table.table_chat.class_6 }}</td>
								<td class="task t6">{{hw_table.table_chat.task_6}}</td>
								<td class="description d6">{{hw_table.table_chat.description_6}}</td>
							</tr>
							<tr>
								<td class="class c7">{{hw_table.table_chat.class_7 }}</td>
								<td class="task t7">{{hw_table.table_chat.task_7}}</td>
								<td class="description d7">{{hw_table.table_chat.description_7}}</td>
							</tr>
							<tr>
								<td class="class c8">{{hw_table.table_chat.class_8 }}</td>
								<td class="task t8">{{hw_table.table_chat.task_8}}</td>
								<td class="description d8">{{hw_table.table_chat.description_8}}</td>
							</tr>
						<a href="#" class="next-day">→</a>
						</table>
						<div class="end-edit">
							<button class="agree" link-to-send-hw="{% url 'mesdb:edit_hw'%}">Сохранить</button>
							<button class="cansel">Отменить изменения</button>
						</div>
						<span id="Modal__close" class="close">ₓ</span>
					</div>

					<div id="HW-Overlay"></div>

				</div>
				{{me.user_login}}
				<img src="{{ me.user_avatar.url }}" class="avatar-img profile-avatar__img">
			</div>
		</div>
		<div class="chat-list">
			<div class="chat-list__top">
				<div class="menu">
			  		<div class="bar1"></div>
			  		<div class="bar2"></div>
			  		<div class="bar3"></div>
			  		<div class="link-bar">
			  			<a href="#" class="l">Настройки</a>
						<a class="profile" href="#" class="l">Профиль</a>
						<a href="#" class="l">Непрочитанные</a>
			  		</div>
			  		
				</div>
				
				<input data=the_user_chats placeholder="Поиск" type="text" class="search">
			</div>
		    <div class="chats">
				{% for i in data %}
					<a base="{% url 'mesdb:index-chat' i.id %}" class="item_chat">
						<img src="{{ i.avatar.url }}" class="avatar-img">
						<div class="link-inf">
							<div class="link-name"><b>{{ i.name }}</b></div>
							<div class="link-last__message">{{ i.last_message }}</div>
						</div>
						<div class="link-inf__end">
							<div class="link-last__time">{{ i.last_message_time }}</div>
							<div class="link-number__unread">
								<div class="unread-plus">{{ i.last_message_unread }}</div>
							</div>
						</div>
					</a>
				{% endfor %}
			</div>
		</div>
		<div class="main-chat">
			<div class="chating-header">
				<div class="back-button">
					<img class="back-img" src="{% static 'img/undo.png' %}">
				</div>
				<div class="chat-name">Не выбран</div>
			</div>
			<div class="chating">
		      	<div class="messages">
					<div class="message-op">
						<div class="empty"></div><br>
						<div class="message op">Выберите чат для начала диалога.</div><br>
						<div class="empty"></div>
					</div>
					<div class="time-breaker">
						<div class="time_breaker">12 мая 2021 года</div>
					</div>
					<div class="message-my">
						<div class="empty"></div><br>
						<div class="empty"></div><br>
					</div>
		      	</div>
			</div>
			<div class="sendler">

			  	<div class="send-input">
			  		
			  		<input type="text" class="send" placeholder="Введите сообщение." id="message-text">

			  	</div>

			  	<button class="send-button" name="sendbtn" data-ajax-target="{% url 'mesdb:sendmessage' %}" token="{{ csrf_token }}" link-to-get="{% url 'mesdb:getmessage' %}" user="{{chat.id}}">
			  		<img src="{% static 'img/send-img.svg' %}" alt="" class="send-button__img">
			  	</button>

			</div>
		</div>

	</div>
	<div class="right-block"></div>
	<div class="settings-sidebar">
		<div class="avatar" style="
			background: url('{{me.user_avatar.url}}');
			background-color: grey;
			background-size: auto 100%;
			background-repeat: no-repeat;
			background-position: center;
		">
		</div>
		<div class="fields">
			<div class="field not-last">
				<div class="field-data nick">{{me.user_login}}</div>
				<div class="field-name">Никнейм</div>
			</div>
			<div class="field">
				<div class="field-data email">f.maksim.2005@gmail.com</div>
				<div class="field-name">Email</div>
			</div>
			<button class="edit-profile__button" active="false">
				<img src="{% static 'img/edit_black_and_white.png' %}" class="edit-profile__img">
			</button>
		</div>
		<div class="transition"></div>
		<div class="additional-info">
			<h2>Разработчик</h2>
			<div class="author-of-project">
				Фомин Максим Александрович
			</div>
		</div>
		<div class="closer">×</div>
	</div>
	<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
	<script src="{% static 'js/index1.js' %}"></script>

	<script>
		$(document).ready(function() {
			$( ".search" ).change(function() {
				var searching = $(this).val()
			    $(".chats").empty();
				
			    {% for i in data  %}
			    	if ("{{i.name}}".includes(searching)){
			    		var myItemChat = 
				    		$('<div class="item_chat" base="{% url 'mesdb:index-chat' i.id %}">' +
						   		'<img src="{{ i.avatar.url }}" class="avatar-img">' +
								'<div class="link-inf">' +
									'<div class="link-name"><b>{{ i.name }}</b></div>' +
									'<div class="link-last__message">{{ i.last_message }}</div>' +
								'</div>' +
								'<div class="link-inf__end">' +
									'<div class="link-last__time">{{ i.last_message_time }}</div>' +
									'<div class="link-number__unread">' +
										'<div class="unread-plus">{{ i.last_message_unread }}</div>' + 
									'</div>' +
								'</div>' +
							'</div>')
							
		                $('.chats').append(myItemChat)
			    	}	
				{% endfor %}

			});
		})
	</script>

{% endblock %}

mymessanger/mymessanger/templates/mesdb/login.html
{% extends "base.html" %}

{% load static %}

{% block title %} Вход {% endblock %}

{% block stylesheets %} 
  <link rel="stylesheet" href="{% static 'css/style.css' %}"> 
{% endblock %}

{% block content %}
  <div class="container">
      {% if form.errors %}
      <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    {% if next %}
      {% if user.is_authenticated %}
        <p>Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</p>
      {% else %}
        <p>Please login to see this page.</p>
      {% endif %}
    {% endif %}

    <form method="post" action="{% url 'mesdb:login' %}">

    {% csrf_token %}

    <div class="links">
      <a class="title" href="{% url 'mesdb:reg' %}">Регестрация</a>
      <div class="title">Вход</div>
    </div>

    <input type="input" class="form-control form-control-login" name="username" id="inputEmail" placeholder="Имя пользователя" required >

    <input type="password" class="form-control form-control-password" name="password" id="inputPass" placeholder="Пароль" required>

    <button class="form-control-button" type="submit" style="opacity: 1 !important;">Войти</button>
    <input type="hidden" name="next" value="{{ next }}" />

    <a class="forgot-pass" href="/password_reset">Забыли пароль?</a>
    </form>

  </div>

{% endblock %}

mymessanger/mymessanger/templates/mesdb/register.html
{% extends "base.html" %}

{% load static %}

{% block title %} Регестрация {% endblock %}

{% block stylesheets %} 
  <link rel="stylesheet" href="{% static 'css/style.css' %}"> 
{% endblock %}

{% block content %}
  <div class="container">

    

    <div class="links">
      <div class="title">Регестрация</div>
      <a class="title" href="{% url 'mesdb:login' %}">Вход</a>
    </div>

    <form action="" method="post">
      {% csrf_token %}
      <input class="form-control" type="text" name="username" id="id_username" placeholder="Имя пользователя" required>

      <input type="password" class="form-control" name="password1" autocomplete="new-password" id="id_password1" placeholder="Пароль" required>

      <input class="form-control" type="password" name="password2" id="id_password2" placeholder="Повторите пароль" required>

      <button class="form-control-button" type="submit">Зарегистрироваться</button>
    </form>

  </div>

{% endblock %}